// <auto-generated />
namespace Small_Shop_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class setProductSpecificationToFalse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(setProductSpecificationToFalse));
        
        string IMigrationMetadata.Id
        {
            get { return "201806091549007_setProductSpecificationToFalse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
